# Generated by Django 4.2.7 on 2023-12-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
