# Generated by Django 4.2.7 on 2023-12-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('en_vente', models.BooleanField(default=False)),
                ('recommande', models.BooleanField(default=False)),
                ('categorie', models.CharField(choices=[('SH', 'SHONEN'), ('AC', 'ACTION'), ('SF', 'SCIENCES_FICTION'), ('AM', 'AMOUR'), ('PS', 'PSYCHOLOGIE'), ('HO', 'HORREUR'), ('HU', 'HUMOUR'), ('FA', 'FANTASTIQUE')], max_length=128)),
                ('Titre', models.CharField(max_length=228)),
                ('Auteur', models.CharField(max_length=128)),
                ('id_User', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images_Livres')),
                ('score', models.IntegerField(default=0)),
                ('nb_lectures', models.IntegerField(default=0)),
                ('Aut_is_User', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
