# Generated by Django 4.2.7 on 2023-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_BOOK_APP', '0002_rename_image_livre_image1_livre_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='livre',
            name='prix',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.CharField(choices=[('SHONEN', 'SHONEN'), ('ACTION', 'ACTION'), ('SCIENCES_FICTION', 'SCIENCES_FICTION'), ('AMOUR', 'AMOUR'), ('PSYCHOLOGIE', 'PSYCHOLOGIE'), ('HORREUR', 'HORREUR'), ('HUMOUR', 'HUMOUR'), ('FANTASTIQUE', 'FANTASTIQUE'), ('', 'AUTRE')], max_length=128),
        ),
        migrations.AlterField(
            model_name='livre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
