# Generated by Django 4.2.7 on 2023-12-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_BOOK_APP', '0003_livre_pdf_livre_prix_alter_livre_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('nom_categorie', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='livre',
            name='nb_lectures',
        ),
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_BOOK_APP.categorie'),
        ),
    ]
