# Generated by Django 4.2.7 on 2023-12-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_BOOK_APP', '0004_categorie_remove_livre_nb_lectures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='prix',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
