# Generated by Django 4.2.7 on 2023-12-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_BOOK_APP', '0005_alter_livre_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='image1',
            field=models.ImageField(upload_to='Images_Livres'),
        ),
    ]
