# Generated by Django 4.2.7 on 2023-12-11 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('E_BOOK_APP', '0009_livre_admincom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='id_User',
        ),
        migrations.AddField(
            model_name='livre',
            name='Aut_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
