# Generated by Django 4.2.7 on 2023-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_BOOK_APP', '0010_remove_livre_id_user_livre_aut_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('livre_id', models.IntegerField()),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('profil', models.ImageField(upload_to='images_Commentaire')),
            ],
        ),
    ]
