# Generated by Django 4.2.7 on 2023-12-11 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('E_BOOK_APP', '0012_rename_livre_id_commentaire_id_livre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='profil',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='posteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
