# Generated by Django 4.2.7 on 2023-12-11 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('E_BOOK_APP', '0013_remove_commentaire_profil_commentaire_posteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('date', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('livre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='E_BOOK_APP.livre')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
