# Generated by Django 4.2.7 on 2023-12-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_BOOK_APP', '0015_alter_lecture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
