# Generated by Django 5.0 on 2023-12-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_BOOK_APP', '0016_livre_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
